# Generated by Django 2.1.7 on 2019-12-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
