# Generated by Django 2.1.7 on 2019-12-31 01:23

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='author',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='country',
            field=django_countries.fields.CountryField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
